language: php
php:
- 5.5

install: composer install
script: phpunit --coverage-clover build/logs/clover.xml
after_script:
  - CODECLIMATE_REPO_TOKEN="994d49d26b49bc06c85c32c84ece534c44d0bad8ae4b86b54ff87172de256788" vendor/bin/test-reporter --stdout > codeclimate.json
  - "curl -X POST -d @codeclimate.json -H 'Content-Type: application/json' -H 'User-Agent: Code Climate (PHP Test Reporter v0.1.1)' https://codeclimate.com/test_reports"